const defaults = { tasks: {}, mastery: {}, studyDay: 1, readingByDay: {}, listeningByDay: {}, materials: [], sessions: [] };
const groups = [
  'achieve|实现;improve|提高;focus|专注;regular|规律的;challenge|挑战;progress|进步;active|积极的;habit|习惯;practice|练习;goal|目标',
  'attend|参加;campus|校园;lecture|讲座;course|课程;library|图书馆;prepare|准备;review|复习;subject|科目;term|学期;graduate|毕业',
  'article|文章;author|作者;detail|细节;explain|解释;main|主要的;meaning|含义;opinion|观点;paragraph|段落;passage|短文;topic|主题',
  'listen|听;recording|录音;repeat|重复;sentence|句子;sound|声音;speaker|说话者;speed|速度;stress|重音;voice|嗓音;understand|理解',
  'benefit|益处;choice|选择;common|常见的;create|创造;develop|发展;effect|效果;example|例子;important|重要的;method|方法;result|结果',
  'community|社区;culture|文化;environment|环境;health|健康;service|服务;society|社会;travel|旅行;volunteer|志愿者;value|价值;world|世界',
  'available|可获得的;compare|比较;continue|继续;decide|决定;increase|增加;manage|管理;notice|注意到;offer|提供;reduce|减少;require|需要',
  'careful|仔细的;confident|自信的;difficult|困难的;effective|有效的;familiar|熟悉的;natural|自然的;patient|耐心的;simple|简单的;useful|有用的;willing|愿意的',
  'build|建立;consider|考虑;discover|发现;encourage|鼓励;follow|遵循;handle|处理;include|包括;measure|衡量;organize|组织;solve|解决',
  'although|虽然;because|因为;however|然而;instead|而是;probably|可能;therefore|因此;usually|通常;whether|是否;while|当…时;within|在…之内',
  'advice|建议;chance|机会;effort|努力;experience|经历;mistake|错误;plan|计划;reason|理由;report|报告;success|成功;support|支持',
  'balance|平衡;communicate|交流;complete|完成;independent|独立的;knowledge|知识;possible|可能的;responsible|负责的;strategy|策略;training|训练;weekly|每周的'
].map(group => group.split(';').map(item => { const [en, zh] = item.split('|'); return [en, '', '核心词', zh, `${en[0].toUpperCase()}${en.slice(1)} is useful in CET-4 study.`]; }));

const lessons = [
  ['学习习惯', 'Small study blocks help students stay focused. A clear plan makes daily practice easier.', '短时学习能帮助学生保持专注。一份清楚的计划会让每天的练习更容易。', 'What makes daily practice easier?', ['A. A clear plan', 'B. A long holiday', 'C. A noisy room'], 'a', 'Why are small study blocks helpful?', ['A. They are expensive', 'B. They help students focus', 'C. They replace sleep'], 'b', 'Study for a short time every day. Your English habit will grow stronger.', '每天学习一小段时间，你的英语习惯会越来越稳。'],
  ['大学课程', 'A student can prepare for a lecture by reading the topic first. This makes class discussion easier to follow.', '学生可以先阅读主题来准备讲座，这会让课堂讨论更容易跟上。', 'What should a student read first?', ['A. The topic', 'B. A novel', 'C. A report card'], 'a', 'What becomes easier?', ['A. Finding a job', 'B. Following discussion', 'C. Leaving campus'], 'b', 'Read the course topic before class, then listen for the main idea.', '课前读课程主题，再听讲座的主旨。'],
  ['阅读主旨', 'The main idea usually appears in the first or last paragraph. Details support the writer’s central point.', '主旨通常出现在第一段或最后一段。细节用来支持作者的中心观点。', 'What supports the central point?', ['A. Details', 'B. Pictures', 'C. Titles only'], 'a', 'Where may the main idea appear?', ['A. Only in the middle', 'B. First or last paragraph', 'C. Nowhere'], 'b', 'First, find the topic. Then look for details that explain it.', '先找到主题，再寻找解释主题的细节。'],
  ['听力步骤', 'Listening improves when learners repeat a short recording. They can notice sounds that were unclear the first time.', '学习者重复听短录音时，听力会提高。他们能注意到第一次没有听清的声音。', 'What can learners notice after repeating?', ['A. New sounds', 'B. The weather', 'C. A new campus'], 'a', 'What should learners repeat?', ['A. A short recording', 'B. A long book', 'C. A map'], 'a', 'Listen once for meaning. Listen again for one sentence you missed.', '第一遍听意思，第二遍专门听漏掉的一句话。'],
  ['有效方法', 'A useful method should fit your daily life. It is better to use one simple method regularly than many methods once.', '有效的方法应该适合你的日常生活。规律使用一种简单方法，比只用一次很多方法更好。', 'What should a method fit?', ['A. Daily life', 'B. A famous person', 'C. A large city'], 'a', 'Which is better?', ['A. Many methods once', 'B. One method regularly', 'C. No method'], 'b', 'Choose one method and use it this week. Small results will appear.', '选择一种方法并坚持一周，小结果会慢慢出现。'],
  ['校园活动', 'Volunteer service gives students a chance to help the community. It also helps them meet people from different backgrounds.', '志愿服务让学生有机会帮助社区，也能让他们认识不同背景的人。', 'Who can students help?', ['A. The community', 'B. Only teachers', 'C. No one'], 'a', 'What else can students do?', ['A. Meet new people', 'B. Stop learning', 'C. Leave school'], 'a', 'A campus volunteer activity can be a useful learning experience.', '校园志愿活动可以成为一次有用的学习经历。'],
  ['时间管理', 'Students need to decide which task is important first. A short list can reduce worry and make time easier to manage.', '学生需要先决定哪项任务更重要。一张简短清单能减少焦虑，让时间更容易管理。', 'What can reduce worry?', ['A. A short list', 'B. More noise', 'C. Less sleep'], 'a', 'What should students decide first?', ['A. The important task', 'B. Their favorite color', 'C. A travel plan'], 'a', 'Write three tasks for today. Start with the most important one.', '写下今天的三项任务，从最重要的一项开始。'],
  ['建立信心', 'Confidence grows from careful practice. A learner does not need to understand every word before trying to speak.', '信心来自仔细练习。学习者不需要在开口前理解每一个词。', 'What helps confidence grow?', ['A. Careful practice', 'B. Waiting forever', 'C. Avoiding English'], 'a', 'What does a learner not need?', ['A. To try speaking', 'B. To understand every word', 'C. To practice'], 'b', 'Speak one simple sentence. Being willing to try matters most.', '说一句简单的话，愿意尝试最重要。'],
  ['解决问题', 'When students make a mistake, they can discover what to practice next. A mistake is useful information, not a final result.', '学生犯错时，可以发现下一步该练什么。错误是有用的信息，不是最终结果。', 'What can a mistake help students discover?', ['A. What to practice', 'B. A new city', 'C. Their height'], 'a', 'A mistake is described as what?', ['A. Final failure', 'B. Useful information', 'C. No information'], 'b', 'Notice one mistake, then organize a small plan to solve it.', '注意一个错误，再制定一个小计划去解决它。'],
  ['连接词', 'Although a passage is short, its connecting words are important. However often shows a different idea, while because gives a reason.', '虽然短文很短，但连接词很重要。however 常表示转折，because 表示原因。', 'Which word gives a reason?', ['A. However', 'B. Because', 'C. While'], 'b', 'What does however often show?', ['A. A different idea', 'B. A number', 'C. A place'], 'a', 'Listen for because and however. They show how two ideas connect.', '注意听 because 和 however，它们显示两个观点如何连接。'],
  ['学习复盘', 'A weekly report helps learners see their effort and progress. It can include one success, one mistake, and one plan for next week.', '每周复盘能帮助学习者看到自己的努力和进步。它可以包括一个成功、一处错误和下周的一个计划。', 'What can a weekly report include?', ['A. One plan for next week', 'B. Only a photo', 'C. No progress'], 'a', 'What does a report help learners see?', ['A. Their effort and progress', 'B. A movie', 'C. A new building'], 'a', 'At the end of the week, write one success and one next step.', '每周结束时，写下一项成功和一个下一步。'],
  ['长期目标', 'A high score needs balanced training in words, reading, listening, and writing. Independent learners adjust their strategy when a plan does not work.', '高分需要词汇、阅读、听力和写作的均衡训练。独立的学习者会在计划无效时调整策略。', 'What does a high score need?', ['A. Balanced training', 'B. One test only', 'C. Luck only'], 'a', 'What do independent learners adjust?', ['A. Their strategy', 'B. The weather', 'C. Their name'], 'a', 'Build knowledge every week. A long-term goal becomes possible through steady training.', '每周积累知识，长期目标会通过稳定训练变得可能。']
].map(([topic, passage, zh, q1, options1, answer1, q2, options2, answer2, listen, listenZh]) => ({ topic, passage, zh, q1, options1, answer1, q2, options2, answer2, listen, listenZh }));

const gloss = { a:'一个', an:'一个', the:'这/那', and:'和', are:'是', as:'作为', be:'是', before:'在…之前', can:'可以', clear:'清楚的', daily:'每天的', does:'助动词', for:'为了', from:'来自', grows:'增长', help:'帮助', helps:'帮助', how:'如何', in:'在', is:'是', it:'它', learn:'学习', learners:'学习者', learning:'学习', make:'使', makes:'使', many:'许多', more:'更多', not:'不', one:'一个', or:'或者', practice:'练习', students:'学生', study:'学习', that:'那个/引导词', them:'他们', then:'然后', they:'他们', this:'这', to:'去/到', useful:'有用的', when:'当…时', with:'和', your:'你的', every:'每一', day:'天', short:'短的', time:'时间', english:'英语', habit:'习惯', will:'将会', stronger:'更强的', first:'首先', main:'主要的', idea:'观点', details:'细节', listening:'听力', reading:'阅读', words:'词汇', word:'词', plan:'计划', small:'小的', easier:'更容易的', important:'重要的', next:'下一步', week:'周', write:'写下', listen:'听', again:'再次', once:'一次', sentence:'句子', missed:'错过的', strong:'强的', build:'建立', knowledge:'知识', through:'通过', steady:'稳定的', training:'训练', high:'高的', score:'分数' };
const taskData = [['vocab','词汇 15 分钟','完成今天的 10 个单词卡'],['reading','阅读 20 分钟','读完短文并做两道题'],['listening','听力 15 分钟','用慢速听 2 遍，再用正常语速听 1 遍']];
let state = load(); let wordIndex = 0;
function load(){ try { return {...defaults, ...JSON.parse(localStorage.getItem('cet4-studio-data')), studyDay: Math.min(12, Math.max(1, Number(JSON.parse(localStorage.getItem('cet4-studio-data'))?.studyDay || 1))) }; } catch { return {...defaults}; } }
function save(){ localStorage.setItem('cet4-studio-data', JSON.stringify(state)); renderHome(); renderProfile(); }
function todayKey(){ const d=new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; }
function markSession(type){ const key=`${todayKey()}-${type}`; if(!state.sessions.includes(key)) state.sessions.push(key); }
function setTodayTask(type, done=true){ const key=todayKey(); state.tasks[key]??={}; state.tasks[key][type]=done; if(done) markSession(type); }
function speak(text, rate=1){ if(!('speechSynthesis' in window)){ alert('当前浏览器不支持朗读功能。'); return; } speechSynthesis.cancel(); const utterance=new SpeechSynthesisUtterance(text); utterance.lang='en-US'; utterance.rate=rate; speechSynthesis.speak(utterance); }
function lesson(){ return lessons[state.studyDay-1]; }
function words(){ const start=state.studyDay-1; return [groups[start],groups[(start+1)%groups.length],groups[(start+2)%groups.length]].flat(); }
function renderHome(){ const key=todayKey(); const list=document.querySelector('#task-list'); list.innerHTML=taskData.map(([id,title,desc])=>`<label class="task ${state.tasks[key]?.[id]?'done':''}"><input type="checkbox" data-task="${id}" ${state.tasks[key]?.[id]?'checked':''}/><span><strong>${title}</strong><small>${desc}</small></span></label>`).join(''); const done=taskData.filter(([id])=>state.tasks[key]?.[id]).length; document.querySelector('#daily-progress').textContent=`${done} / 3`; document.querySelector('#progress-bar').style.width=`${done/3*100}%`; document.querySelector('#daily-message').textContent=done===3?'今天的学习已完成，收得很漂亮。':done?'继续保持，把下一项做完。':'从第一项开始就好。'; const labels=['一','二','三','四','五','六','日']; const day=new Date().getDay(); const todayIndex=day===0?6:day-1; document.querySelector('#week-chart').innerHTML=labels.map((label,i)=>`<div class="${i===todayIndex?'today':''}"><i style="height:${i===todayIndex?70:24+i%3*18}px"></i>${label}</div>`).join(''); }
function renderWord(){ const list=words(); const w=list[wordIndex]; ['word-en','word-phonetic','word-tag','word-zh','word-example'].forEach((id,i)=>document.querySelector('#'+id).textContent=w[[0,1,2,3,4][i]]); document.querySelector('#word-index').textContent=`${wordIndex+1} / ${list.length}`; document.querySelector('#word-card').classList.remove('flipped'); document.querySelector('#word-feedback').textContent=''; const review=groups.flat().filter(w=>state.mastery[w[0]]==='review'); document.querySelector('#review-count').textContent=review.length; document.querySelector('#review-words').innerHTML=review.length?review.map(w=>`<span class="review-word">${w[0]} · ${w[3]}</span>`).join(''):'<p class="muted">还没有待复习单词。遇到不熟的词时，点“还不熟”就会放在这里。</p>'; }
function interlinear(text){ const list=text.match(/[A-Za-z]+(?:'[A-Za-z]+)?|[.,!?]/g)||[]; return `<div class="interlinear">${list.map(token=>{ const lower=token.toLowerCase(); const meaning=groups.flat().find(w=>w[0]===lower)?.[3] || gloss[lower] || (/[.,!?]/.test(token)?'':'词语提示'); return `<span><b>${escapeHtml(token)}</b><small>${escapeHtml(meaning)}</small></span>`; }).join('')}</div>`; }
function renderLesson(){ const item=lesson(); document.querySelector('#day-label').textContent=`第 ${state.studyDay} 天 · 10 个词`; document.querySelector('#reading-content').innerHTML=`<p>${item.passage}</p>`; document.querySelector('#reading-translation').innerHTML=`<p class="translation-zh">${item.zh}</p><p class="translation-tip">词语提示用于对照理解，整句意思以上方中文为准。</p>${interlinear(item.passage)}`; document.querySelector('#reading-questions').innerHTML=questionHtml('q1',item.q1,item.options1)+questionHtml('q2',item.q2,item.options2); document.querySelector('#reading-result').textContent=''; document.querySelector('#mark-reading').textContent=state.readingByDay[state.studyDay]?'✓ 已标记为完成':'标记今天阅读完成'; document.querySelector('#listening-number').textContent=`第 ${state.studyDay} 天 · ${item.topic}`; document.querySelector('#listening-topic').textContent='短句精听'; document.querySelector('#listening-text').textContent=item.listen; document.querySelector('#listening-translation').innerHTML=`<p class="translation-zh">${item.listenZh}</p><p class="translation-tip">词语提示用于对照理解，整句意思以上方中文为准。</p>${interlinear(item.listen)}`; const listenDone=document.querySelector('#listening-done'); listenDone.checked=!!state.listeningByDay[state.studyDay]; }
function questionHtml(name, question, options){ return `<fieldset><legend>${question}</legend>${options.map((option,i)=>`<label><input type="radio" name="${name}" value="${String.fromCharCode(97+i)}"> ${option}</label>`).join('')}</fieldset>`; }
function renderProfile(){ const learned=Object.values(state.mastery).filter(v=>v==='known').length; const sessions=state.sessions.filter(x=>x.startsWith(todayKey())).length; document.querySelector('#stats').innerHTML=`<div class="stat"><strong>${learned}</strong><small>已经掌握的词</small></div><div class="stat"><strong>${sessions}</strong><small>今天完成的练习</small></div><div class="stat"><strong>${state.materials.length}</strong><small>已导入的材料</small></div>`; document.querySelector('#material-list').innerHTML=state.materials.length?state.materials.map((m,i)=>`<div class="material"><span>📄 ${escapeHtml(m.name)} <small>(${m.type})</small></span><button data-remove-material="${i}" aria-label="删除 ${escapeHtml(m.name)}">删除</button></div>`).join(''):'<p class="muted">还没有材料。可以先导入课堂笔记或练习文本。</p>'; }
function escapeHtml(text){ const d=document.createElement('div');d.textContent=text;return d.innerHTML; }
function showView(name){ document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===name)); document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name)); window.scrollTo({top:0,behavior:'smooth'}); }
function changeDay(delta){ state.studyDay=Math.min(12,Math.max(1,state.studyDay+delta)); wordIndex=0; save(); renderWord(); renderLesson(); renderHighIntensity(); }
document.addEventListener('click',e=>{ const button=e.target.closest('[data-view]'); if(button) showView(button.dataset.view); const remove=e.target.closest('[data-remove-material]'); if(remove){state.materials.splice(Number(remove.dataset.removeMaterial),1);save();} });
document.querySelector('#task-list').addEventListener('change',e=>{if(e.target.dataset.task){const key=todayKey();state.tasks[key]??={};state.tasks[key][e.target.dataset.task]=e.target.checked;if(e.target.checked)markSession(e.target.dataset.task);save();}});
document.querySelector('#previous-day').onclick=()=>changeDay(-1); document.querySelector('#next-day').onclick=()=>changeDay(1);
const card=document.querySelector('#word-card'); card.addEventListener('click',e=>{if(!e.target.closest('button'))card.classList.toggle('flipped')}); card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();card.classList.toggle('flipped')}}); document.querySelector('#next-word').onclick=()=>{wordIndex=(wordIndex+1)%words().length;renderWord()};document.querySelector('#previous-word').onclick=()=>{wordIndex=(wordIndex+words().length-1)%words().length;renderWord()};document.querySelector('#speak-word').onclick=()=>speak(words()[wordIndex][0]);
document.querySelectorAll('[data-mastery]').forEach(b=>b.onclick=()=>{state.mastery[words()[wordIndex][0]]=b.dataset.mastery;setTodayTask('vocab');save();renderWord();document.querySelector('#word-feedback').textContent=b.dataset.mastery==='known'?'已记为“我会了”。':'已放入待复习。';});
document.querySelector('#reading-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);const item=lesson();const score=(f.get('q1')===item.answer1?1:0)+(f.get('q2')===item.answer2?1:0);document.querySelector('#reading-result').textContent=score===2?'全对。你抓住了主旨和细节！':`答对 ${score}/2。正确答案是 1-${item.answer1.toUpperCase()}、2-${item.answer2.toUpperCase()}。回到文章找对应句。`;if(score===2){state.readingByDay[state.studyDay]=true;setTodayTask('reading');save();}}); document.querySelector('#mark-reading').onclick=()=>{state.readingByDay[state.studyDay]=true;setTodayTask('reading');save();document.querySelector('#mark-reading').textContent='✓ 已标记为完成';};document.querySelector('#speak-passage').onclick=()=>speak(lesson().passage,.88);
function togglePanel(id, button){ const panel=document.querySelector(id); const hidden=panel.hidden; panel.hidden=!hidden; button.textContent=hidden?'收起中文对照':'显示中文对照'; }
document.querySelector('#toggle-reading-translation').onclick=e=>togglePanel('#reading-translation',e.currentTarget); document.querySelector('#toggle-listening-translation').onclick=e=>togglePanel('#listening-translation',e.currentTarget);
document.querySelector('#play-listening').onclick=()=>speak(lesson().listen,Number(document.querySelector('#speech-rate').value)); document.querySelector('#toggle-transcript').onclick=e=>{const text=document.querySelector('#listening-text');text.classList.toggle('hidden');e.target.textContent=text.classList.contains('hidden')?'显示文字':'隐藏文字';}; const listenDone=document.querySelector('#listening-done');listenDone.onchange=()=>{state.listeningByDay[state.studyDay]=listenDone.checked;if(listenDone.checked)setTodayTask('listening');save();};
document.querySelector('#material-input').addEventListener('change',async e=>{const files=[...e.target.files];for(const file of files){if(file.size>500000){alert(`${file.name} 超过 500KB，第一版建议导入较小的文本文件。`);continue;}state.materials.push({name:file.name,type:file.name.endsWith('.md')?'Markdown':'TXT',content:await file.text(),addedAt:new Date().toISOString()});}save();e.target.value='';});
document.querySelector('#export-data').onclick=()=>{const blob=new Blob([JSON.stringify({version:2,exportedAt:new Date().toISOString(),data:state},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`cet4-study-backup-${todayKey()}.json`;a.click();URL.revokeObjectURL(a.href);document.querySelector('#backup-feedback').textContent='备份已下载。请把它保存在容易找到的位置。';}; document.querySelector('#import-data').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const imported=JSON.parse(await file.text());if(!imported.data)throw new Error();state={...defaults,...imported.data,readingByDay:imported.data.readingByDay||{},listeningByDay:imported.data.listeningByDay||{}};save();renderWord();renderLesson();document.querySelector('#backup-feedback').textContent='数据已导入。';}catch{document.querySelector('#backup-feedback').textContent='这个文件无法识别，请选择从本网站导出的 JSON 备份。';}e.target.value='';});
document.querySelector('#today-date').textContent=new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long'}).format(new Date());renderHome();renderWord();renderProfile();renderLesson();

function readingSet(){ const item=lesson(); const additions=[
  'Students often begin with too many goals at once. A better choice is to select one clear action and repeat it for several days. This makes progress easier to notice and gives learners a reason to continue.',
  'A useful notebook records more than new words. It can also keep questions, small mistakes, and one sentence that was difficult to understand. Looking back at these notes helps learners choose their next practice.',
  'Learning becomes stronger when students check their own work. They can ask what the passage is mainly about, which detail supports it, and which word connects two ideas. This short review builds reading confidence.'
 ];
 return additions.map((addition,i)=>({title:`阅读 ${i+1}`,text:`${item.passage} ${addition}`,zh:`${item.zh} ${['学生不必一次做太多；选择一个明确动作并重复，会更容易看到进步。','笔记除了记录单词，也能记录问题、错误和难句，帮助安排下一步练习。','通过确认主旨、细节和连接词，学习者可以慢慢建立阅读信心。'][i]}`,correct:['main idea','detail','connection'][i]}));
}
function readingCard(reading,index){ const names=['主旨是什么？','文中建议学习者怎么做？','这篇文章主要强调什么？']; const options=index===0?['用小而明确的行动持续练习','一天完成所有内容','不记录学习过程']:index===1?['记录问题和难句','只记住标题','不需要回看笔记']:['检查主旨、细节和连接词','跳过所有细节','只翻译每个单词']; return `<article class="paper-card reading-item"><p class="eyebrow">${reading.title.toUpperCase()} · MEDIUM LENGTH</p><p class="reading-copy">${reading.text}</p><button type="button" class="text-btn" data-read-speak="${index}">朗读文章</button><button type="button" class="text-btn" data-toggle-read="${index}">显示中文与逐词对照</button><div class="translation-panel" id="read-translation-${index}" hidden><p class="translation-zh">${reading.zh}</p><p class="translation-tip">词语提示用于对照理解，整句意思以上方中文为准。</p>${interlinear(reading.text)}</div><fieldset class="questions"><legend>${names[index]}</legend>${options.map((v,i)=>`<label><input type="radio" name="r${index}" value="${i}"> ${String.fromCharCode(65+i)}. ${v}</label>`).join('')}</fieldset></article>`; }
function listeningSet(){ const list=words().slice(0,10); return list.map((word,i)=>({word, text:`The key word in this short practice is ${word[0]}. Please repeat it after the speaker.`})); }
function listeningCard(item,index){ const options=[item.word[0],words()[(index+7)%30][0],words()[(index+14)%30][0]].sort(); return `<article class="paper-card listening-item"><div class="tape"><span>SHORT LISTENING ${String(index+1).padStart(2,'0')}</span><span>关键词辨音</span></div><p class="listen-sentence">${item.text}</p><button type="button" class="round-play" data-listen-play="${index}" aria-label="播放第 ${index+1} 道">▶</button><button type="button" class="text-btn" data-toggle-listen="${index}">显示中文与逐词对照</button><div class="translation-panel" id="listen-translation-${index}" hidden><p class="translation-zh">本题关键词：${item.word[0]}（${item.word[3]}）。请听清并跟读。</p>${interlinear(item.text)}</div><fieldset class="questions"><legend>你听到的关键词是哪一个？</legend>${options.map(v=>`<label><input type="radio" name="l${index}" value="${v}"> ${v}</label>`).join('')}</fieldset></article>`; }
function renderHighIntensity(){ const readings=readingSet(), listenings=listeningSet(); document.querySelector('#day-label').textContent=`第 ${state.studyDay} 天 · 30 个词`; document.querySelector('#reading-list').innerHTML=readings.map(readingCard).join(''); document.querySelector('#listening-list').innerHTML=listenings.map(listeningCard).join(''); document.querySelector('#reading-result').textContent=''; }
document.addEventListener('click',e=>{ const r=e.target.closest('[data-read-speak]'); if(r) speak(readingSet()[Number(r.dataset.readSpeak)].text,.88); const rt=e.target.closest('[data-toggle-read]'); if(rt) togglePanel(`#read-translation-${rt.dataset.toggleRead}`,rt); const lp=e.target.closest('[data-listen-play]'); if(lp) speak(listeningSet()[Number(lp.dataset.listenPlay)].text,Number(document.querySelector('#speech-rate').value)); const lt=e.target.closest('[data-toggle-listen]'); if(lt) togglePanel(`#listen-translation-${lt.dataset.toggleListen}`,lt); });
document.querySelector('#reading-form').addEventListener('submit',e=>{ const form=new FormData(e.currentTarget); const readingScore=readingSet().reduce((sum,_,i)=>sum+(form.get(`r${i}`)==='0'?1:0),0); document.querySelector('#reading-result').textContent=`阅读答对 ${readingScore}/3。每篇先抓主旨，再回文中找细节。`; if(readingScore===3){state.readingByDay[state.studyDay]=true;setTodayTask('reading');save();} });
document.querySelector('#check-listening').onclick=()=>{ const score=listeningSet().reduce((sum,item,i)=>sum+(document.querySelector(`input[name="l${i}"]:checked`)?.value===item.word[0]?1:0),0); document.querySelector('#listening-result').textContent=`短精听答对 ${score}/10。错题建议用 0.8 倍再听两遍。`; if(score===10){state.listeningByDay[state.studyDay]=true;setTodayTask('listening');save();} };
renderHighIntensity();

