const defaults = { tasks: {}, mastery: {}, readingDone: false, listeningDone: false, materials: [], sessions: [] };
const words = [
  ['achieve','/əˈtʃiːv/','verb','实现；达到','Small steps can achieve big goals.'],
  ['improve','/ɪmˈpruːv/','verb','提高；改善','Reading every day can improve your English.'],
  ['focus','/ˈfəʊkəs/','verb','集中注意力','Try to focus on one task at a time.'],
  ['regular','/ˈreɡjələ(r)/','adjective','规律的；定期的','Regular practice builds confidence.'],
  ['challenge','/ˈtʃælɪndʒ/','noun','挑战','A new word can be a small challenge.'],
  ['progress','/ˈprəʊɡres/','noun','进步；进展','You can see progress after a few weeks.']
];
const taskData = [['vocab','词汇 15 分钟','完成今天的 6 个单词卡'],['reading','阅读 20 分钟','读完短文并做两道题'],['listening','听力 15 分钟','用慢速听 2 遍，再用正常语速听 1 遍']];
let state = load(); let wordIndex = 0;
function load(){ try { return {...defaults, ...JSON.parse(localStorage.getItem('cet4-studio-data'))}; } catch { return {...defaults}; } }
function save(){ localStorage.setItem('cet4-studio-data', JSON.stringify(state)); renderHome(); renderProfile(); }
function todayKey(){ const d=new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; }
function markSession(type){ const key=`${todayKey()}-${type}`; if(!state.sessions.includes(key)) state.sessions.push(key); }
function setTodayTask(type, done=true){ const key=todayKey(); state.tasks[key]??={}; state.tasks[key][type]=done; if(done) markSession(type); }
function speak(text, rate=1){ if(!('speechSynthesis' in window)){ alert('当前浏览器不支持朗读功能。'); return; } speechSynthesis.cancel(); const utterance=new SpeechSynthesisUtterance(text); utterance.lang='en-US'; utterance.rate=rate; speechSynthesis.speak(utterance); }
function renderHome(){ const key=todayKey(); const list=document.querySelector('#task-list'); list.innerHTML=taskData.map(([id,title,desc])=>`<label class="task ${state.tasks[key]?.[id]?'done':''}"><input type="checkbox" data-task="${id}" ${state.tasks[key]?.[id]?'checked':''}/><span><strong>${title}</strong><small>${desc}</small></span></label>`).join(''); const done=taskData.filter(([id])=>state.tasks[key]?.[id]).length; document.querySelector('#daily-progress').textContent=`${done} / 3`; document.querySelector('#progress-bar').style.width=`${done/3*100}%`; document.querySelector('#daily-message').textContent=done===3?'今天的学习已完成，收得很漂亮。':done?'继续保持，把下一项做完。':'从第一项开始就好。';
  const labels=['一','二','三','四','五','六','日']; const day=new Date().getDay(); const todayIndex=day===0?6:day-1; document.querySelector('#week-chart').innerHTML=labels.map((label,i)=>`<div class="${i===todayIndex?'today':''}"><i style="height:${i===todayIndex?70:24+i%3*18}px"></i>${label}</div>`).join(''); }
function renderWord(){ const w=words[wordIndex]; ['word-en','word-phonetic','word-tag','word-zh','word-example'].forEach((id,i)=>document.querySelector('#'+id).textContent=w[[0,1,2,3,4][i]]); document.querySelector('#word-index').textContent=`${wordIndex+1} / ${words.length}`; document.querySelector('#word-card').classList.remove('flipped'); document.querySelector('#word-feedback').textContent=''; const review=words.filter(w=>state.mastery[w[0]]==='review'); document.querySelector('#review-count').textContent=review.length; document.querySelector('#review-words').innerHTML=review.length?review.map(w=>`<span class="review-word">${w[0]} · ${w[3]}</span>`).join(''):'<p class="muted">还没有待复习单词。遇到不熟的词时，点“还不熟”就会放在这里。</p>'; }
function renderProfile(){ const learned=Object.values(state.mastery).filter(v=>v==='known').length; const sessions=state.sessions.filter(x=>x.startsWith(todayKey())).length; document.querySelector('#stats').innerHTML=`<div class="stat"><strong>${learned}</strong><small>已经掌握的词</small></div><div class="stat"><strong>${sessions}</strong><small>今天完成的练习</small></div><div class="stat"><strong>${state.materials.length}</strong><small>已导入的材料</small></div>`; document.querySelector('#material-list').innerHTML=state.materials.length?state.materials.map((m,i)=>`<div class="material"><span>📄 ${escapeHtml(m.name)} <small>(${m.type})</small></span><button data-remove-material="${i}" aria-label="删除 ${escapeHtml(m.name)}">删除</button></div>`).join(''):'<p class="muted">还没有材料。可以先导入课堂笔记或练习文本。</p>'; }
function escapeHtml(text){ const d=document.createElement('div');d.textContent=text;return d.innerHTML; }
function showView(name){ document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===name)); document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name)); window.scrollTo({top:0,behavior:'smooth'}); }
document.addEventListener('click',e=>{ const button=e.target.closest('[data-view]'); if(button) showView(button.dataset.view); const remove=e.target.closest('[data-remove-material]'); if(remove){state.materials.splice(Number(remove.dataset.removeMaterial),1);save();} });
document.querySelector('#task-list').addEventListener('change',e=>{if(e.target.dataset.task){const key=todayKey();state.tasks[key]??={};state.tasks[key][e.target.dataset.task]=e.target.checked;if(e.target.checked)markSession(e.target.dataset.task);save();}});
const card=document.querySelector('#word-card'); card.addEventListener('click',e=>{if(!e.target.closest('button'))card.classList.toggle('flipped')}); card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();card.classList.toggle('flipped')}}); document.querySelector('#next-word').onclick=()=>{wordIndex=(wordIndex+1)%words.length;renderWord()};document.querySelector('#previous-word').onclick=()=>{wordIndex=(wordIndex+words.length-1)%words.length;renderWord()};document.querySelector('#speak-word').onclick=()=>speak(words[wordIndex][0]);
document.querySelectorAll('[data-mastery]').forEach(b=>b.onclick=()=>{state.mastery[words[wordIndex][0]]=b.dataset.mastery;setTodayTask('vocab');save();renderWord();document.querySelector('#word-feedback').textContent=b.dataset.mastery==='known'?'已记为“我会了”。':'已放入待复习。';});
document.querySelector('#reading-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);const score=(f.get('q1')==='b'?1:0)+(f.get('q2')==='a'?1:0);document.querySelector('#reading-result').textContent=score===2?'全对。你抓住了主旨和细节！':`答对 ${score}/2。正确答案是 1-B、2-A。回到文章找对应句。`;if(score===2){state.readingDone=true;setTodayTask('reading');save();}}); document.querySelector('#mark-reading').onclick=()=>{state.readingDone=true;setTodayTask('reading');save();document.querySelector('#mark-reading').textContent='✓ 已标记为完成';};document.querySelector('#speak-passage').onclick=()=>speak('Many students believe that they need long hours to learn English well. In fact, short and regular study sessions can be more helpful. When learners study for thirty to sixty minutes, they are often able to stay focused. They can review a few words, read one short passage, and listen to a simple recording. The key is to return to English every day. A notebook can help learners notice their progress. After several weeks, small efforts become a strong habit.',.88);
document.querySelector('#play-listening').onclick=()=>speak(document.querySelector('#listening-text').textContent,Number(document.querySelector('#speech-rate').value)); document.querySelector('#toggle-transcript').onclick=e=>{const text=document.querySelector('#listening-text');text.classList.toggle('hidden');e.target.textContent=text.classList.contains('hidden')?'显示文字':'隐藏文字';}; const listenDone=document.querySelector('#listening-done');listenDone.checked=state.listeningDone;listenDone.onchange=()=>{state.listeningDone=listenDone.checked;if(listenDone.checked)setTodayTask('listening');save();};
document.querySelector('#material-input').addEventListener('change',async e=>{const files=[...e.target.files];for(const file of files){if(file.size>500000){alert(`${file.name} 超过 500KB，第一版建议导入较小的文本文件。`);continue;}state.materials.push({name:file.name,type:file.name.endsWith('.md')?'Markdown':'TXT',content:await file.text(),addedAt:new Date().toISOString()});}save();e.target.value='';});
document.querySelector('#export-data').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),data:state},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`cet4-study-backup-${todayKey()}.json`;a.click();URL.revokeObjectURL(a.href);document.querySelector('#backup-feedback').textContent='备份已下载。请把它保存在容易找到的位置。';}; document.querySelector('#import-data').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const imported=JSON.parse(await file.text());if(!imported.data)throw new Error();state={...defaults,...imported.data};save();renderWord();listenDone.checked=state.listeningDone;document.querySelector('#backup-feedback').textContent='数据已导入。';}catch{document.querySelector('#backup-feedback').textContent='这个文件无法识别，请选择从本网站导出的 JSON 备份。';}e.target.value='';});
document.querySelector('#today-date').textContent=new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long'}).format(new Date());renderHome();renderWord();renderProfile();

